"""
XBRL metric registry and data-selection logic (pure functions, no network access).

Shared by two consumers:
  1. ``src/tools/sec_edgar.py`` — turns SEC ``companyfacts`` JSON into structured values the agent can read;
  2. ``evaluation/finance/gold.py`` — generates the evaluation gold from the same kind of data.

Important XBRL details (pitfalls, handled in select_period):
  * ``fy`` / ``fp`` describe the fiscal year / period of the **filing** (DocumentFiscalYearFocus), not of the period the value belongs to.
    One 10-K holds both the current and the prior-period comparative values; they share the same ``fy`` but have different ``end``.
    So the filing (accn) must be locked first, then current / prior picked by ``end`` and duration.
  * Flow metrics (revenue, net income, cash flow) must be filtered by duration: ~365 days for a year, ~91 days for a quarter;
    a 10-Q also carries 6-month and 9-month cumulative values, which would be picked wrongly without filtering.
  * Stock metrics (total assets, cash) are point-in-time values and have no ``start``.
  * The same fact may be disclosed repeatedly by several filings (including 10-K/A amendments); only original 10-K / 10-Q are used here,
    and when one period has several rows the latest ``filed`` wins.
"""
from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import date

__all__ = [
    "METRICS",
    "FactValue",
    "metric_names",
    "resolve_metric",
    "select_period",
    "format_value",
]


# kind: flow = flow over a period; instant = point-in-time stock
# unit: the key under units in companyfacts
# en / zh: common phrasings in report text, used for the evaluation's heuristic mapping and the tool's fuzzy matching (the Chinese aliases are intentional)
METRICS: dict[str, dict] = {
    "revenue": {
        "concepts": ["RevenueFromContractWithCustomerExcludingAssessedTax", "Revenues", "SalesRevenueNet", "SalesRevenueGoodsNet"],
        "kind": "flow", "unit": "USD",
        "en": ["total net sales", "net sales", "total revenues", "total revenue", "revenues", "revenue", "sales"],
        "zh": ["营业总收入", "营业收入", "总收入", "净销售额", "营收", "收入", "销售额"],
    },
    "cost_of_revenue": {
        "concepts": ["CostOfRevenue", "CostOfGoodsAndServicesSold", "CostOfGoodsSold"],
        "kind": "flow", "unit": "USD",
        "en": ["cost of revenue", "cost of sales", "cost of goods sold", "cogs"],
        "zh": ["营业成本", "销售成本", "主营业务成本", "成本"],
    },
    "gross_profit": {
        "concepts": ["GrossProfit"],
        "kind": "flow", "unit": "USD",
        "en": ["gross profit", "gross margin dollars"],
        "zh": ["毛利润", "毛利"],
    },
    "operating_income": {
        "concepts": ["OperatingIncomeLoss"],
        "kind": "flow", "unit": "USD",
        "en": ["operating income", "income from operations", "operating profit"],
        "zh": ["营业利润", "经营利润", "营业收益"],
    },
    "net_income": {
        "concepts": ["NetIncomeLoss", "ProfitLoss", "NetIncomeLossAvailableToCommonStockholdersBasic"],
        "kind": "flow", "unit": "USD",
        "en": ["net income", "net earnings", "net profit"],
        "zh": ["归属于母公司股东的净利润", "归母净利润", "净利润", "净收益", "净利"],
    },
    "eps_diluted": {
        "concepts": ["EarningsPerShareDiluted"],
        "kind": "flow", "unit": "USD/shares", "per_share": True,
        "en": ["diluted eps", "diluted earnings per share", "earnings per share", "eps"],
        "zh": ["稀释每股收益", "稀释后每股收益", "每股收益", "每股盈利"],
    },
    "rd_expense": {
        "concepts": ["ResearchAndDevelopmentExpense", "ResearchAndDevelopmentExpenseExcludingAcquiredInProcessCost"],
        "kind": "flow", "unit": "USD",
        "en": ["research and development", "r&d expense", "r&d"],
        "zh": ["研发费用", "研发支出", "研发投入"],
    },
    "sga_expense": {
        "concepts": ["SellingGeneralAndAdministrativeExpense"],
        "kind": "flow", "unit": "USD",
        "en": ["selling, general and administrative", "sg&a"],
        "zh": ["销售及管理费用", "销售、一般及行政费用", "销售管理费用"],
    },
    "operating_cash_flow": {
        "concepts": ["NetCashProvidedByUsedInOperatingActivities"],
        "kind": "flow", "unit": "USD",
        "en": ["operating cash flow", "cash from operations", "cash generated by operating activities"],
        "zh": ["经营活动现金流", "经营性现金流", "经营现金流"],
    },
    "capex": {
        "concepts": ["PaymentsToAcquirePropertyPlantAndEquipment", "PaymentsToAcquireProductiveAssets"],
        "kind": "flow", "unit": "USD",
        "en": ["capital expenditures", "capex", "purchases of property, plant and equipment"],
        "zh": ["资本支出", "资本开支"],
    },
    "total_assets": {
        "concepts": ["Assets"],
        "kind": "instant", "unit": "USD",
        "en": ["total assets"],
        "zh": ["总资产", "资产总额", "资产总计"],
    },
    "total_liabilities": {
        "concepts": ["Liabilities"],
        "kind": "instant", "unit": "USD",
        "en": ["total liabilities"],
        "zh": ["总负债", "负债总额", "负债合计"],
    },
    "stockholders_equity": {
        "concepts": ["StockholdersEquity", "StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest"],
        "kind": "instant", "unit": "USD",
        "en": ["shareholders' equity", "stockholders' equity", "total equity", "shareholders equity"],
        "zh": ["股东权益", "所有者权益", "净资产"],
    },
    "cash_and_equivalents": {
        "concepts": ["CashAndCashEquivalentsAtCarryingValue", "CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents"],
        "kind": "instant", "unit": "USD",
        "en": ["cash and cash equivalents", "cash and equivalents"],
        "zh": ["现金及现金等价物", "货币资金", "现金及等价物"],
    },
    "long_term_debt": {
        "concepts": ["LongTermDebtNoncurrent", "LongTermDebt"],
        "kind": "instant", "unit": "USD",
        "en": ["long-term debt", "long term debt"],
        "zh": ["长期债务", "长期借款", "长期负债"],
    },
    "diluted_shares": {
        "concepts": ["WeightedAverageNumberOfDilutedSharesOutstanding"],
        "kind": "flow", "unit": "shares", "count": True,
        "en": ["diluted shares", "weighted average diluted shares"],
        "zh": ["稀释后加权平均股数", "稀释股数"],
    },
}


def metric_names() -> list[str]:
    return list(METRICS)


def resolve_metric(name: str) -> str | None:
    """Resolve a metric name given by a user/model (English or Chinese aliases, us-gaap concept names) to a registry key."""
    if not name:
        return None
    key = name.strip().lower().replace(" ", "_").replace("-", "_")
    if key in METRICS:
        return key
    low = name.strip().lower()
    for k, spec in METRICS.items():
        if any(low == c.lower() for c in spec["concepts"]):
            return k
        if low in [a.lower() for a in spec["en"]] or name.strip() in spec["zh"]:
            return k
    return None


@dataclass
class FactValue:
    metric: str
    concept: str
    unit: str
    value: float
    period_label: str  # "FY2023" / "Q2 FY2024"
    start: str | None
    end: str
    form: str
    accn: str
    filed: str
    fy: int
    fp: str

    def to_dict(self) -> dict:
        return asdict(self)


def _d(s: str | None) -> date | None:
    try:
        return date.fromisoformat(s) if s else None
    except ValueError:
        return None


def _duration_ok(kind: str, start: str | None, end: str, fp: str) -> bool:
    if kind == "instant":
        return True
    ds, de = _d(start), _d(end)
    if not ds or not de:
        return False
    days = (de - ds).days
    if fp == "FY":
        return 350 <= days <= 380
    return 80 <= days <= 100  # single quarter (excludes 6M/9M cumulative)


def _entries(facts: dict, concept: str, unit: str) -> list[dict]:
    node = facts.get("facts", {}).get("us-gaap", {}).get(concept)
    if not node:
        return []
    return list(node.get("units", {}).get(unit, []))


def select_period(
    companyfacts: dict,
    metric: str,
    fiscal_year: int,
    fiscal_period: str = "FY",
) -> list[FactValue]:
    """From companyfacts, get a metric's current value and prior-year comparative for (fiscal year, fiscal period).

    Returns:
        At most two FactValue: [current, prior-year] (omitted if not found). Returns an empty list if the current value is not found.
    """
    spec = METRICS.get(metric)
    if spec is None:
        return []
    kind, unit = spec["kind"], spec["unit"]
    want_forms = {"FY": {"10-K"}}.get(fiscal_period, {"10-Q"})

    for concept in spec["concepts"]:
        rows = [
            r for r in _entries(companyfacts, concept, unit)
            if r.get("form") in want_forms
            and r.get("fy") == fiscal_year
            and r.get("fp") == fiscal_period
            and r.get("end")
        ]
        if not rows:
            continue

        # lock the filing: one fiscal period may have several (including repeated disclosures); take the accn with the latest filed
        latest_accn = max(rows, key=lambda r: (r.get("filed", ""), r.get("accn", ""))).get("accn")
        in_filing = [r for r in rows if r.get("accn") == latest_accn and _duration_ok(kind, r.get("start"), r["end"], fiscal_period)]
        if not in_filing:
            continue

        cur_end = max(r["end"] for r in in_filing)
        cur = next(r for r in in_filing if r["end"] == cur_end)
        out = [_to_fact(metric, concept, unit, cur, fiscal_year, fiscal_period, current=True)]

        # prior-year period: the row in the same filing whose end is about one year earlier (+-20 days)
        ce = _d(cur_end)
        prior = None
        for r in in_filing:
            re_ = _d(r["end"])
            if ce and re_ and 345 <= (ce - re_).days <= 385:
                prior = r
                break
        if prior is not None:
            out.append(_to_fact(metric, concept, unit, prior, fiscal_year - 1, fiscal_period, current=False))
        return out
    return []


def _label(fy: int, fp: str) -> str:
    return f"FY{fy}" if fp == "FY" else f"{fp} FY{fy}"


def _to_fact(metric: str, concept: str, unit: str, row: dict, fy: int, fp: str, current: bool) -> FactValue:
    return FactValue(
        metric=metric,
        concept=concept,
        unit=unit,
        value=float(row["val"]),
        period_label=_label(fy, fp),
        start=row.get("start"),
        end=row["end"],
        form=row.get("form", ""),
        accn=row.get("accn", ""),
        filed=row.get("filed", ""),
        fy=fy,
        fp=fp,
    )


def format_value(value: float, unit: str) -> str:
    """Human/model-readable form, e.g. 383285000000 USD -> '383,285.0 million USD'."""
    if unit == "USD":
        a = abs(value)
        if a >= 1e9:
            return f"{value / 1e6:,.1f} million USD (= {value / 1e9:,.3f} billion)"
        if a >= 1e6:
            return f"{value / 1e6:,.1f} million USD"
        return f"{value:,.0f} USD"
    if unit == "USD/shares":
        return f"{value:.2f} USD per share"
    if unit == "shares":
        return f"{value / 1e6:,.1f} million shares" if abs(value) >= 1e6 else f"{value:,.0f} shares"
    return f"{value:,} {unit}"
